baseURL = "https://shirasu-oisi.github.io/rust-library/"
languageCode = "ja"
title = "My New Hugo Site"
theme = "book"
publishDir = "docs"

[taxonomies]
tag = "tags"

[params]
BookMenuBundle = "/menu"